### ISSUE TITLE
Should show `input.renderBody`

### ISSUE THREAD

**Issue by jsumners** [marko-js-samples/marko-custom-tags#1]
There should be an example using `input.renderBody` that illustrates how to create a tag for:

``` html
<div class=data.classes>
  This sentence would be filled in by `input.renderBody`.
</div>
```

**Comment by patrick-steele-idem** [comment]
``` xml
<div class=data.classes>
  <invoke input.renderBody(out) if(input.renderBody)/>
</div>
```

I agree there should be an example so keeping this issue open. If you want to send a PR that would be awesome :)
